// Generated by Skyramp v1.3.27 on 2026-06-18 18:21:21.103946387 +0000 UTC m=+550.281382996
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output dark_mode_mealplanner.spec.ts \
// 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie-testb/mealie-testb/.skyramp/dark_mode_mealplanner_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(395000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/shopping-lists");
    await page.goto("http://localhost:9000/g/home");
    await page.goto("http://localhost:9000/login");
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.getByRole("button", { name: "Login" }).click();
    await page.locator("main").getByRole("link", { name: "I'm already set up" }).click();
    await page.goto("http://localhost:9000/household/mealplan/planner/view");
    await expect(page).toHaveURL(/\/mealplan\/planner\/view/);
    await expect(page.getByRole("tab", { name: "Meal Planner" })).toHaveAttribute("aria-selected", "true");
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
    expect(errors).toHaveLength(0);
});
