// Generated by Skyramp v1.3.27 on 2026-06-18 18:46:27.202795648 +0000 UTC m=+593.107147518
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_delete_confirm.spec.ts \
// 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie-testb/mealie-testb/.skyramp/recipe_delete_confirm_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(687000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    await page.goto("http://localhost:9000/login");
    await page.waitForLoadState('networkidle');
    await page.locator("#username").fill("changeme@example.com");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.waitForLoadState('networkidle');
    await page.locator("main").getByRole("link", { name: "I\\" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.locator("main").getByRole("link", { name: "I\\" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(15000);

    await page.getByRole("link", { name: "Test Delete Recipe ☆ ☆ ☆ ☆ ☆" }).hover();
    await page.getByRole("link", { name: "I\\" }).click();
    await page.keyboard.press("Escape");
    await page.locator("a").locator(".v-btn--size-default").click();
    await page.locator(".text-center > .v-btn").click();
    await expect(page.getByTestId("recipe-delete-confirm")).toContainText("Are you sure you want to delete this recipe?");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/recipes/**");
    await page.getByText("Delete", { exact: true }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(204);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("main")).toContainText("Recipes");
    await expect(page).toHaveURL(/\/g\/home/);
    await expect(page.getByRole("link", { name: "Test Delete Recipe ☆ ☆ ☆ ☆ ☆" })).not.toBeVisible();
    expect(errors).toHaveLength(0);
});
