// Generated by Skyramp v1.3.27 on 2026-06-18 18:46:31.65606512 +0000 UTC m=+597.560416990
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output recipe_delete_cancel.spec.ts \
// 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie-testb/mealie-testb/.skyramp/recipe_delete_cancel_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(120000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    await page.goto("http://localhost:9000/login");
    await page.waitForLoadState('networkidle');
    await page.locator("#username").fill("changeme@example.com");
    await page.locator("#password").fill("MyPassword");
    await page.getByRole("button", { name: "Login" }).click();
    await page.waitForLoadState('networkidle');
    await page.locator("main").getByRole("link", { name: "I\\" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.locator("main").getByRole("link", { name: "I\\" }).click();
    await page.goto("http://localhost:9000/g/home/r/test-cancel-delete-recipe");
    await page.waitForSelector("text=Test Cancel Delete Recipe");
    await page.getByRole("link", { name: "I\\" }).click();
    await page.locator(".text-center > .v-btn").click();
    await expect(page.getByTestId("recipe-delete-confirm")).toContainText("Are you sure you want to delete this recipe?");
    await page.getByText("Delete", { exact: true }).click();
    await page.getByRole("button", { name: "Cancel" }).click();
    await expect(page).toHaveURL(/test-cancel-delete-recipe/);
    await expect(page.getByText("Test Cancel Delete Recipe")).toBeVisible();
    expect(errors).toHaveLength(0);
});
