// Generated by Skyramp v1.3.27 on 2026-06-18 18:18:35.90969554 +0000 UTC m=+385.087132139
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/mealie-testb/mealie-testb/.skyramp/dark_mode_initial_attr_trace.zip

// Import of required libraries
import { test, expect, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(415000);

    const errors: Error[] = [];
    page.on('pageerror', (err) => errors.push(err));

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:9000/login");
    await page.getByRole("button", { name: "Login" }).click();
    await page.locator("main").getByRole("link", { name: "I'm already set up" }).click();
    await expect(page.getByRole("main")).toContainText("Recipes");
    await expect(page).toHaveURL(/\/g\/home/);
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
    await page.goto("http://localhost:9000/user/profile");
    await page.goto("http://localhost:9000/user/profile/edit");
    await expect(page.getByRole("heading", { name: "User Settings" })).toHaveText("User Settings");
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
    expect(errors).toHaveLength(0);
});
