# Generated by Skyramp v1.3.17 on 2026-06-16 14:13:35.913115784 +0000 UTC m=+262.952336575
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output backups_unique_constraint_integration_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie-testb/mealie-testb/tests/scenario_backups-unique-constraint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    backups_POST_request_body = r'''{}'''
    
    # Execute Request
    backups_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/backups",
        method="POST",
        body=backups_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert backups_POST_response.status_code == 201
    assert skyramp.get_response_value(backups_POST_response, "message") is not None

    # Request Body
    backups_POST_1_request_body = r'''{}'''
    
    # Execute Request
    backups_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/backups",
        method="POST",
        body=backups_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert backups_POST_1_response.status_code == 409

    # Execute Request
    backups_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/backups",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert backups_GET_response.status_code == 200
    assert skyramp.get_response_value(backups_GET_response, "imports") is not None
    assert skyramp.get_response_value(backups_GET_response, "templates") is not None


if __name__ == "__main__":
    test_integration()
