# Generated by Skyramp v1.3.27 on 2026-06-18 13:24:55.661371065 +0000 UTC m=+205.503310814
# Command: skyramp generate contract rest http://localhost:9000/api/recipes/statistics \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_recipe_statistics_unauth_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

# contract test for /api/recipes/statistics GET
def test_statistics_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header - intentionally empty to test unauthenticated access
    headers = {}

    # Execute Request
    statistics_GET_response = client.send_request(
        url=URL,
        path="/api/recipes/statistics",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert statistics_GET_response.status_code == 401
    assert skyramp.get_response_value(statistics_GET_response, "detail") is not None


if __name__ == "__main__":
    test_statistics_get()
