# Generated by Skyramp v1.3.27 on 2026-06-18 10:53:30.214048837 +0000 UTC m=+436.740640817
# Command: skyramp generate contract rest http://localhost:9000/api/recipes \
# 		--api-schema http://localhost:9000/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_post_recipes_negative_servings.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"negative-servings-contract-test","recipeServings":-1} \
# 		--response-status-code 422 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

# contract test for /api/recipes POST
def test_recipes_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    recipes_POST_request_body = r'''{
        "name": "negative-servings-contract-test",
        "recipeServings": -1
    }'''

    # Expected Response Body
    expected_recipes_POST_response_body = r'''{
        "detail": [
            {
                "loc": [
                    "body",
                    "recipeServings"
                ],
                "msg": "Value error, recipe_servings and recipe_yield_quantity must be non-negative",
                "type": "value_error"
            }
        ]
    }'''

    # Execute Request
    recipes_POST_response = client.send_request(
        url=URL,
        path="/api/recipes",
        method="POST",
        body=recipes_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert recipes_POST_response.status_code == 422
    assert skyramp.check_schema(recipes_POST_response, expected_recipes_POST_response_body)
    assert skyramp.get_response_value(recipes_POST_response, "detail.0.loc.0") is not None
    assert skyramp.get_response_value(recipes_POST_response, "detail.0.msg") is not None
    assert skyramp.get_response_value(recipes_POST_response, "detail.0.type") is not None
    assert skyramp.get_response_value(recipes_POST_response, "detail.0.loc.0") == "body"
    assert skyramp.get_response_value(recipes_POST_response, "detail.0.type") == "value_error"
    assert skyramp.get_response_value(recipes_POST_response, "detail.0.msg") == "Value error, recipe_servings and recipe_yield_quantity must be non-negative"
    assert skyramp.get_response_value(recipes_POST_response, "detail.1") is None


if __name__ == "__main__":
    test_recipes_post()
