# Generated by Skyramp v1.3.27 on 2026-06-18 13:24:46.333466954 +0000 UTC m=+196.175406703
# Command: skyramp generate contract rest http://localhost:9000/api/recipes/statistics \
# 		--api-schema http://localhost:9000/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_recipe_statistics_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

# contract test for /api/recipes/statistics GET
def test_statistics_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_statistics_GET_response_body = r'''{
        "by_category": {},
        "total": 1
    }'''

    # Execute Request
    statistics_GET_response = client.send_request(
        url=URL,
        path="/api/recipes/statistics",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert statistics_GET_response.status_code == 200
    assert skyramp.check_schema(statistics_GET_response, expected_statistics_GET_response_body)
    assert skyramp.get_response_value(statistics_GET_response, "total") is not None
    assert skyramp.get_response_value(statistics_GET_response, "total") >= 0
    assert skyramp.get_response_value(statistics_GET_response, "by_category") is not None


if __name__ == "__main__":
    test_statistics_get()
