# Generated by Skyramp v1.3.17 on 2026-06-17 17:07:42.062713825 +0000 UTC m=+183.440080130
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output openai_unique_constraint_integration_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie-testb/mealie-testb/tests/scenario_openai-unique-constraint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    openai_00000000_0000_0000_0000_000000000001_POST_request_body = r'''{}'''
    
    # Execute Request
    openai_00000000_0000_0000_0000_000000000001_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/debug/openai/00000000-0000-0000-0000-000000000001",
        method="POST",
        body=openai_00000000_0000_0000_0000_000000000001_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert openai_00000000_0000_0000_0000_000000000001_POST_response.status_code == 201
    assert skyramp.get_response_value(openai_00000000_0000_0000_0000_000000000001_POST_response, "success") is not None

    # Request Body
    openai_00000000_0000_0000_0000_000000000001_POST_1_request_body = r'''{}'''

    # Execute Request
    openai_00000000_0000_0000_0000_000000000001_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/debug/openai/00000000-0000-0000-0000-000000000001",
        method="POST",
        body=openai_00000000_0000_0000_0000_000000000001_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert openai_00000000_0000_0000_0000_000000000001_POST_1_response.status_code == 409


if __name__ == "__main__":
    test_integration()
