# Generated by Skyramp v1.3.17 on 2026-06-17 17:32:39.836140717 +0000 UTC m=+489.778517421
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output openai_unique_constraint_integration_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie-testb/mealie-testb/tests/scenario_openai-unique-constraint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    f47ac10b_58cc_4372_a567_0e02b2c3d479_POST_request_body = r'''{}'''
    
    # Execute Request
    f47ac10b_58cc_4372_a567_0e02b2c3d479_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/debug/openai/f47ac10b-58cc-4372-a567-0e02b2c3d479",
        method="POST",
        body=f47ac10b_58cc_4372_a567_0e02b2c3d479_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert f47ac10b_58cc_4372_a567_0e02b2c3d479_POST_response.status_code == 200
    assert skyramp.get_response_value(f47ac10b_58cc_4372_a567_0e02b2c3d479_POST_response, "success") is not None

    # Request Body
    f47ac10b_58cc_4372_a567_0e02b2c3d479_POST_1_request_body = r'''{}'''

    # Execute Request
    f47ac10b_58cc_4372_a567_0e02b2c3d479_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/admin/debug/openai/f47ac10b-58cc-4372-a567-0e02b2c3d479",
        method="POST",
        body=f47ac10b_58cc_4372_a567_0e02b2c3d479_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert f47ac10b_58cc_4372_a567_0e02b2c3d479_POST_1_response.status_code == 200
    assert skyramp.get_response_value(f47ac10b_58cc_4372_a567_0e02b2c3d479_POST_1_response, "success") is not None


if __name__ == "__main__":
    test_integration()
