# Generated by Skyramp v1.3.27 on 2026-06-18 13:29:13.409362647 +0000 UTC m=+471.388477384
# Command: skyramp generate contract rest http://localhost:9000/api/parser/ingredient \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output parser_ingredient_contract_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"ingredient":"3/4 cup flour","parser":"nlp"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

# contract test for /api/parser/ingredient POST
def test_ingredient_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    ingredient_POST_request_body = r'''{
        "ingredient": "3/4 cup flour",
        "parser": "nlp"
    }'''

    # Execute Request
    ingredient_POST_response = client.send_request(
        url=URL,
        path="/api/parser/ingredient",
        method="POST",
        body=ingredient_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(ingredient_POST_response, "20x")
    assert ingredient_POST_response.status_code == 200
    assert skyramp.get_response_value(ingredient_POST_response, "input") == "3/4 cup flour"
    assert skyramp.get_response_value(ingredient_POST_response, "ingredient") is not None


if __name__ == "__main__":
    test_ingredient_post()
