# Generated by Skyramp v1.3.27 on 2026-06-18 13:29:16.422069394 +0000 UTC m=+474.401184131
# Command: skyramp generate contract rest http://localhost:9000/api/parser/ingredients \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output parser_ingredients_bulk_contract_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"parser":"nlp","ingredients":["3/4 cup flour","1/2 tsp salt","2 1/4 cups sugar"]} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

# contract test for /api/parser/ingredients POST
def test_ingredients_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    ingredients_POST_request_body = r'''{
        "ingredients": [
            "3/4 cup flour",
            "1/2 tsp salt",
            "2 1/4 cups sugar"
        ],
        "parser": "nlp"
    }'''

    # Execute Request
    ingredients_POST_response = client.send_request(
        url=URL,
        path="/api/parser/ingredients",
        method="POST",
        body=ingredients_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(ingredients_POST_response, "20x")
    assert ingredients_POST_response.status_code == 200
    assert skyramp.get_response_value(ingredients_POST_response, "0.input") == "3/4 cup flour"
    assert skyramp.get_response_value(ingredients_POST_response, "1.input") == "1/2 tsp salt"
    assert skyramp.get_response_value(ingredients_POST_response, "2.input") == "2 1/4 cups sugar"


if __name__ == "__main__":
    test_ingredients_post()
