# Generated by Skyramp v1.3.27 on 2026-06-18 13:29:26.187907685 +0000 UTC m=+484.167022422
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output recipe_lifecycle_fraction_display_integration_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie-testb/mealie-testb/tests/scenario_recipe-lifecycle-fraction-display.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    recipes = "test-fraction"

    # Request Body
    recipes_POST_request_body = r'''{
        "name": "test-fraction"
    }'''
    
    # Execute Request
    recipes_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="POST",
        body=recipes_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert recipes_POST_response.status_code == 201

    # Execute Request
    recipes_recipes_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/{recipes}",
        method="GET",
        headers=headers,
        path_params={"recipes": recipes}
    )
    # Generated Assertions
    assert recipes_recipes_GET_response.status_code == 200
    assert skyramp.get_response_value(recipes_recipes_GET_response, "name") == "test-fraction"
    assert skyramp.get_response_value(recipes_recipes_GET_response, "slug") == "test-fraction"
    assert skyramp.get_response_value(recipes_recipes_GET_response, "id") is not None

    # Execute Request
    recipes_recipes_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/{recipes}",
        method="DELETE",
        headers=headers,
        path_params={"recipes": skyramp.get_response_value(recipes_recipes_GET_response, "slug")}
    )
    # Generated Assertions
    assert recipes_recipes_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
