# Generated by Skyramp v1.3.27 on 2026-06-18 13:29:24.115131865 +0000 UTC m=+521.333971350
# Command: skyramp generate contract rest http://localhost:9000/api/recipes \
# 		--api-schema http://localhost:9000/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output recipes_categories_only_contract_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--query-params categories_only=true \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

# contract test for /api/recipes GET
def test_recipes_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_recipes_GET_response_body = r'''{
        "items": [
            {
                "cookTime": "1h 30m",
                "createdAt": "2024-01-01T12:00:00Z",
                "dateAdded": "2024-01-01",
                "dateUpdated": "2024-01-01",
                "description": "",
                "groupId": "00000000-0000-0000-0000-000000000000",
                "householdId": "00000000-0000-0000-0000-000000000000",
                "id": "00000000-0000-0000-0000-000000000000",
                "image": "recipe.jpg",
                "lastMade": "2024-01-01T12:00:00Z",
                "name": "Test Recipe",
                "orgURL": "https://example.com/recipe",
                "performTime": "30m",
                "prepTime": "15m",
                "rating": 4.5,
                "recipeCategory": [],
                "recipeServings": 4,
                "recipeYield": "4 servings",
                "recipeYieldQuantity": 4,
                "slug": "test-recipe",
                "tags": [],
                "tools": [
                    {
                        "id": "00000000-0000-0000-0000-000000000000",
                        "name": "Oven",
                        "slug": "oven"
                    }
                ],
                "totalTime": "2h",
                "updatedAt": "2024-01-01T12:00:00Z",
                "userId": "00000000-0000-0000-0000-000000000000"
            }
        ]
    }'''

    # Execute Request
    recipes_GET_response = client.send_request(
        url=URL,
        path="/api/recipes",
        method="GET",
        headers=headers,
        query_params={"categories_only": "true"}
    )

    # Generated Assertions
    assert recipes_GET_response.status_code == 200
    assert skyramp.check_schema(recipes_GET_response, expected_recipes_GET_response_body)
    if skyramp.get_response_value(recipes_GET_response, "total") > 0:
        assert skyramp.get_response_value(recipes_GET_response, "items.0.cookTime") is not None
        assert skyramp.get_response_value(recipes_GET_response, "items.0.createdAt") is not None
        assert skyramp.get_response_value(recipes_GET_response, "items.0.dateAdded") is not None
    assert skyramp.get_response_value(recipes_GET_response, "page") >= 1
    assert skyramp.get_response_value(recipes_GET_response, "per_page") >= 1
    assert skyramp.get_response_value(recipes_GET_response, "total") >= 0


if __name__ == "__main__":
    test_recipes_get()
