# Generated by Skyramp v1.3.27 on 2026-06-18 10:53:47.8088587 +0000 UTC m=+454.335450680
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output recipe_negative_yield_put_validation_integration_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie-testb/mealie-testb/tests/scenario_recipe-negative-yield-put-validation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    name = "recipe-negative-yield-put"

    # Request Body
    recipes_POST_request_body = r'''{
        "name": "recipe-negative-yield-put"
    }'''
    
    # Execute Request
    recipes_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="POST",
        body=recipes_POST_request_body,
        headers=headers,
        data_override={"name": name}
    )
    # Generated Assertions
    assert recipes_POST_response.status_code == 201

    # Request Body
    recipes_recipes_PUT_request_body = r'''{
        "name": "recipe-negative-yield-put",
        "recipeYieldQuantity": -1
    }'''
    
    # Execute Request
    recipes_recipes_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/{recipes}",
        method="PUT",
        body=recipes_recipes_PUT_request_body,
        headers=headers,
        path_params={"recipes": name},
        data_override={"name": name}
    )
    # Generated Assertions
    assert recipes_recipes_PUT_response.status_code == 422
    assert skyramp.get_response_value(recipes_recipes_PUT_response, "detail.0.type") == "value_error"
    assert skyramp.get_response_value(recipes_recipes_PUT_response, "detail.0.msg") is not None
    assert skyramp.get_response_value(recipes_recipes_PUT_response, "detail.1") is None

    # Execute Request
    recipes_recipes_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/{recipes}",
        method="GET",
        headers=headers,
        path_params={"recipes": name}
    )
    # Generated Assertions
    assert recipes_recipes_GET_response.status_code == 200
    assert skyramp.get_response_value(recipes_recipes_GET_response, "name") == "recipe-negative-yield-put"
    assert skyramp.get_response_value(recipes_recipes_GET_response, "slug") is not None
    assert skyramp.get_response_value(recipes_recipes_GET_response, "recipeYieldQuantity") == 0


if __name__ == "__main__":
    test_integration()
