# Generated by Skyramp v1.3.27 on 2026-06-18 13:34:57.064189239 +0000 UTC m=+227.998142238
# Command: skyramp generate contract rest http://localhost:9000/api/recipes \
# 		--api-schema http://localhost:9000/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output recipes_list_contract_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

# contract test for /api/recipes GET
def test_recipes_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_recipes_GET_response_body = r'''{
        "items": [
            {
                "cookTime": "string",
                "createdAt": "string",
                "dateAdded": "string",
                "dateUpdated": "string",
                "description": "",
                "groupId": "string",
                "householdId": "string",
                "id": "string",
                "image": "string",
                "lastMade": "string",
                "name": "string",
                "orgURL": "string",
                "performTime": "string",
                "prepTime": "string",
                "rating": "string",
                "recipeCategory": "",
                "recipeServings": 0,
                "recipeYield": "string",
                "recipeYieldQuantity": 0,
                "slug": "",
                "tags": "",
                "tools": [
                    {
                        "id": "string",
                        "name": "string",
                        "slug": "string"
                    }
                ],
                "totalTime": "string",
                "updatedAt": "string",
                "userId": "string"
            }
        ]
    }'''

    # Execute Request
    recipes_GET_response = client.send_request(
        url=URL,
        path="/api/recipes",
        method="GET",
        headers=headers,
        query_params={
            "categories": None,
            "cookbook": None,
            "foods": None,
            "households": None,
            "orderBy": None,
            "orderByNullPosition": None,
            "orderDirection": None,
            "page": 1,
            "paginationSeed": None,
            "perPage": 50,
            "queryFilter": None,
            "requireAllCategories": False,
            "requireAllFoods": False,
            "requireAllTags": False,
            "requireAllTools": False,
            "search": None,
            "tags": None,
            "tools": None
        }
    )

    # Generated Assertions
    assert recipes_GET_response.status_code == 200
    assert skyramp.get_response_value(recipes_GET_response, "page") == 1
    assert skyramp.get_response_value(recipes_GET_response, "per_page") == 50
    assert skyramp.get_response_value(recipes_GET_response, "total") >= 0
    assert isinstance(skyramp.get_response_value(recipes_GET_response, "items"), list)


if __name__ == "__main__":
    test_recipes_get()
