# Generated by Skyramp v1.3.27 on 2026-06-18 13:24:57.491519266 +0000 UTC m=+207.333459015
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output recipe_statistics_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie-testb/mealie-testb/tests/scenario_recipe-statistics-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    recipes_POST_request_body = r'''{
        "name": "stats-test-recipe"
    }'''
    
    # Execute Request
    recipes_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="POST",
        body=recipes_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert recipes_POST_response.status_code == 201

    # Execute Request
    statistics_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/statistics",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert statistics_GET_response.status_code == 200
    assert skyramp.get_response_value(statistics_GET_response, "total") is not None
    assert skyramp.get_response_value(statistics_GET_response, "total") >= 1
    assert skyramp.get_response_value(statistics_GET_response, "by_category") is not None


if __name__ == "__main__":
    test_integration()
