# Generated by Skyramp v1.3.27 on 2026-06-18 13:35:03.332978671 +0000 UTC m=+848.280237352
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output recipe_time_fields_count_recalculate_integration_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie-testb/mealie-testb/tests/scenario_recipe-time-fields-count-recalculate.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    name = "no-time-fields-recipe"

    # Request Body
    recipes_POST_request_body = r'''{
        "name": "no-time-fields-recipe"
    }'''
    
    # Execute Request
    recipes_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="POST",
        body=recipes_POST_request_body,
        headers=headers,
        data_override={"name": name}
    )
    # Generated Assertions
    assert recipes_POST_response.status_code == 201
    assert skyramp.get_response_value(recipes_POST_response, "") == name

    # Execute Request
    recipes_recipes_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/{recipes}",
        method="GET",
        headers=headers,
        path_params={"recipes": name}
    )
    # Generated Assertions
    assert recipes_recipes_GET_response.status_code == 200
    assert skyramp.get_response_value(recipes_recipes_GET_response, "name") == "no-time-fields-recipe"
    assert skyramp.get_response_value(recipes_recipes_GET_response, "slug") == name
    assert skyramp.get_response_value(recipes_recipes_GET_response, "timeFieldsCount") == 0

    # Request Body
    recipes_recipes_PATCH_request_body = r'''{
        "cookTime": "1 hr",
        "prepTime": "30 mins"
    }'''
    
    # Execute Request
    recipes_recipes_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/{recipes}",
        method="PATCH",
        body=recipes_recipes_PATCH_request_body,
        headers=headers,
        path_params={"recipes": name}
    )
    # Generated Assertions
    assert recipes_recipes_PATCH_response.status_code == 200
    assert skyramp.get_response_value(recipes_recipes_PATCH_response, "prepTime") == "30 mins"
    assert skyramp.get_response_value(recipes_recipes_PATCH_response, "cookTime") == "1 hr"
    assert skyramp.get_response_value(recipes_recipes_PATCH_response, "timeFieldsCount") == 2

    # Execute Request
    recipes_recipes_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/{recipes}",
        method="GET",
        headers=headers,
        path_params={"recipes": name}
    )
    # Generated Assertions
    assert recipes_recipes_GET_1_response.status_code == 200
    assert skyramp.get_response_value(recipes_recipes_GET_1_response, "slug") == name
    assert skyramp.get_response_value(recipes_recipes_GET_1_response, "prepTime") == "30 mins"
    assert skyramp.get_response_value(recipes_recipes_GET_1_response, "cookTime") == "1 hr"
    assert skyramp.get_response_value(recipes_recipes_GET_1_response, "timeFieldsCount") == 2


if __name__ == "__main__":
    test_integration()
