# Generated by Skyramp v1.3.27 on 2026-06-18 13:34:48.961411472 +0000 UTC m=+833.908670143
# Command: skyramp generate contract rest http://localhost:9000/api/recipes \
# 		--api-schema http://localhost:9000/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output recipes_contract_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

# contract test for /api/recipes GET
def test_recipes_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_recipes_GET_response_body = r'''{
        "items": [
            {
                "timeFieldsCount": 0
            }
        ]
    }'''

    # Execute Request
    recipes_GET_response = client.send_request(
        url=URL,
        path="/api/recipes",
        method="GET",
        headers=headers,
        query_params={
            "categories": None,
            "cookbook": None,
            "foods": None,
            "households": None,
            "orderBy": None,
            "orderByNullPosition": None,
            "orderDirection": None,
            "page": 1,
            "paginationSeed": None,
            "perPage": 50,
            "queryFilter": None,
            "requireAllCategories": False,
            "requireAllFoods": False,
            "requireAllTags": False,
            "requireAllTools": False,
            "search": None,
            "tags": None,
            "tools": None
        }
    )

    # Generated Assertions
    assert recipes_GET_response.status_code == 200
    assert skyramp.check_schema(recipes_GET_response, expected_recipes_GET_response_body)
    assert skyramp.get_response_value(recipes_GET_response, "page") == 1
    assert skyramp.get_response_value(recipes_GET_response, "per_page") == 50
    assert skyramp.get_response_value(recipes_GET_response, "items") is not None
    assert skyramp.get_response_value(recipes_GET_response, "items.0.timeFieldsCount") is not None


if __name__ == "__main__":
    test_recipes_get()
