# Generated by Skyramp v1.3.27 on 2026-06-18 13:35:02.88757362 +0000 UTC m=+847.834832291
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output recipe_time_fields_count_partial_integration_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie-testb/mealie-testb/tests/scenario_recipe-time-fields-count-partial.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    name = "partial-time-recipe"

    # Request Body
    recipes_POST_request_body = r'''{
        "name": "partial-time-recipe"
    }'''
    
    # Execute Request
    recipes_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="POST",
        body=recipes_POST_request_body,
        headers=headers,
        data_override={"name": name}
    )
    # Generated Assertions
    assert recipes_POST_response.status_code == 201
    assert skyramp.get_response_value(recipes_POST_response, "") == name

    # Execute Request
    recipes_recipes_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/{recipes}",
        method="GET",
        headers=headers,
        path_params={"recipes": name}
    )
    # Generated Assertions
    assert recipes_recipes_GET_response.status_code == 200
    assert skyramp.get_response_value(recipes_recipes_GET_response, "slug") == name
    assert skyramp.get_response_value(recipes_recipes_GET_response, "name") == "partial-time-recipe"
    assert skyramp.get_response_value(recipes_recipes_GET_response, "prepTime") is None
    assert skyramp.get_response_value(recipes_recipes_GET_response, "cookTime") is None
    assert skyramp.get_response_value(recipes_recipes_GET_response, "timeFieldsCount") == 0
    assert skyramp.get_response_value(recipes_recipes_GET_response, "id") is not None


if __name__ == "__main__":
    test_integration()
