# Generated by Skyramp v1.3.27 on 2026-06-18 10:53:46.409706696 +0000 UTC m=+452.936298666
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output recipe_negative_servings_patch_validation_integration_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie-testb/mealie-testb/tests/scenario_recipe-negative-servings-patch-validation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    recipes = "recipe-negative-servings-patch"

    # Request Body
    recipes_POST_request_body = r'''{
        "name": "recipe-negative-servings-patch"
    }'''
    
    # Execute Request
    recipes_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="POST",
        body=recipes_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert recipes_POST_response.status_code == 201

    # Request Body
    recipes_recipes_PATCH_request_body = r'''{
        "recipeServings": -1
    }'''
    
    # Execute Request
    recipes_recipes_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/{recipes}",
        method="PATCH",
        body=recipes_recipes_PATCH_request_body,
        headers=headers,
        path_params={"recipes": recipes}
    )
    # Generated Assertions
    assert recipes_recipes_PATCH_response.status_code == 422
    assert skyramp.get_response_value(recipes_recipes_PATCH_response, "detail.0.type") == "value_error"
    assert skyramp.get_response_value(recipes_recipes_PATCH_response, "detail.0.msg") is not None
    assert skyramp.get_response_value(recipes_recipes_PATCH_response, "detail.1") is None

    # Execute Request
    recipes_recipes_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/{recipes}",
        method="GET",
        headers=headers,
        path_params={"recipes": recipes}
    )
    # Generated Assertions
    assert recipes_recipes_GET_response.status_code == 200
    assert skyramp.get_response_value(recipes_recipes_GET_response, "name") == "recipe-negative-servings-patch"
    assert skyramp.get_response_value(recipes_recipes_GET_response, "slug") is not None
    assert skyramp.get_response_value(recipes_recipes_GET_response, "recipeServings") == 0


if __name__ == "__main__":
    test_integration()
