# Generated by Skyramp v1.3.27 on 2026-06-18 13:29:35.70466166 +0000 UTC m=+532.923501152
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output recipes_categories_only_filter_integration_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/mealie-testb/mealie-testb/tests/scenario_recipes-categories-only-filter.json

# Import of required libraries
import skyramp
import os
import time
import re


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    ts = str(int(time.time()))
    category_name = "SkyTestCat-" + ts
    category_slug = "skytestcat-" + ts
    recipe_name = "SkyTestRecipeCat-" + ts
    recipe_slug = "skytestrecipecat-" + ts

    # Declaration of variables
    recipes = recipe_slug

    # Request Body
    categories_POST_request_body = '{"name": "' + category_name + '"}'

    # Execute Request
    categories_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/organizers/categories",
        method="POST",
        body=categories_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert categories_POST_response.status_code == 201
    assert skyramp.get_response_value(categories_POST_response, "name") == category_name
    assert skyramp.get_response_value(categories_POST_response, "slug") == category_slug
    assert re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', skyramp.get_response_value(categories_POST_response, "id") or "", re.IGNORECASE)

    # Request Body
    recipes_POST_request_body = '{"name": "' + recipe_name + '"}'

    # Execute Request
    recipes_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="POST",
        body=recipes_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert recipes_POST_response.status_code == 201

    cat_id = str(skyramp.get_response_value(categories_POST_response, "id") or "")
    # Request Body
    recipes_recipes_PATCH_request_body = '{"name": "' + recipe_name + '", "recipeCategory": [{"id": "' + cat_id + '", "name": "' + category_name + '", "slug": "' + category_slug + '"}], "slug": "' + recipe_slug + '"}'

    # Execute Request
    recipes_recipes_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes/{recipes}",
        method="PATCH",
        body=recipes_recipes_PATCH_request_body,
        headers=headers,
        path_params={"recipes": recipes},
        data_override={"slug": recipes}
    )
    # Generated Assertions
    assert recipes_recipes_PATCH_response.status_code == 200
    assert skyramp.get_response_value(recipes_recipes_PATCH_response, "name") == recipe_name
    assert skyramp.get_response_value(recipes_recipes_PATCH_response, "slug") == recipe_slug
    assert skyramp.get_response_value(recipes_recipes_PATCH_response, "recipeCategory.0.name") == category_name
    assert skyramp.get_response_value(recipes_recipes_PATCH_response, "recipeCategory.0.slug") == category_slug
    assert skyramp.get_response_value(recipes_recipes_PATCH_response, "recipeCategory.0.id") == skyramp.get_response_value(categories_POST_response, "id")

    # Execute Request
    recipes_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/recipes",
        method="GET",
        headers=headers,
        query_params={"categories_only": ["true"]}
    )
    # Generated Assertions
    assert recipes_GET_response.status_code == 200
    assert skyramp.get_response_value(recipes_GET_response, "page") >= 1
    assert skyramp.get_response_value(recipes_GET_response, "per_page") >= 1
    assert skyramp.get_response_value(recipes_GET_response, "total") >= 1
    assert skyramp.get_response_value(recipes_GET_response, "items.0") is not None


if __name__ == "__main__":
    test_integration()
