# Generated by Skyramp v1.3.27 on 2026-06-18 13:34:45.386069445 +0000 UTC m=+216.320022422
# Command: skyramp generate contract rest http://localhost:9000/api/recipes/suggestions \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output suggestions_removed_contract_test.py \
# 		--output-dir /home/runner/work/mealie-testb/mealie-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 404 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:9000")

# contract test for /api/recipes/suggestions GET
def test_suggestions_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    suggestions_GET_response = client.send_request(
        url=URL,
        path="/api/recipes/suggestions",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert suggestions_GET_response.status_code == 404
    assert skyramp.get_response_value(suggestions_GET_response, "detail.message") == "No Entry Found"
    assert skyramp.get_response_value(suggestions_GET_response, "detail.error") == True


if __name__ == "__main__":
    test_suggestions_get()
